"""add_recovery_attempts_table

Revision ID: b475926cf903
Revises: f5d842ede85a
Create Date: 2026-08-27 17:58:14.340137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b475926cf903'
down_revision: Union[str, Sequence[str], None] = 'f5d842ede85a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_attempts_id'), 'recovery_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_attempts_payment_id'), 'recovery_attempts', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_attempts_payment_id'), table_name='recovery_attempts')
    op.drop_index(op.f('ix_recovery_attempts_id'), table_name='recovery_attempts')
    op.drop_table('recovery_attempts')
    # ### end Alembic commands ###
